version : "2"

services:
  app:
    build : app
    ports:
      - "80:8080"
    volumes:
      - ./app:/code
    depends_on:
      - mongo  
  mongo:
    image : mongo
    ports:
      - "27017:27017"
